[keys]
quit = "q"
cursor-left = ["h", "<Left>"]
cursor-down = ["j", "<Down>"]
cursor-up = ["k", "<Up>"]
cursor-right = ["l", "<Right>"]
# "volume set +5" = "+"
# "volume set -5" = "-"
# "play toggle" = "<Space>"

[theme]
