[keys]
quit = "q"
cursor-left = ["h", "<Left>"]
cursor-down = ["j", "<Down>"]
cursor-up = ["k", "<Up>"]
cursor-right = ["l", "<Right>"]
# "volume set +5" = "+"
# "volume set -5" = "-"
# "play toggle" = "<Space>"

[theme.colours]
background = "#1e1e2e"
overlay = "#313244"
border-active = "#b4befe"
border-inactive = "#6c7086"
