[package]
name = "zankyou-parser"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true
zankyou-macros.workspace = true
